/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _CLOCK_CONFIG_H_
#define _CLOCK_CONFIG_H_

#include "fsl_common.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/
#define BOARD_XTAL0_CLK_HZ                         32000000U  /*!< Board xtal0 frequency in Hz */

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes default configuration of clocks.
 *
 */
void BOARD_InitBootClocks(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 *************************** Configuration clk_init ****************************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for clk_init configuration
 ******************************************************************************/
#define CLK_INIT_CORE_CLOCK                        96000000U  /*!< Core clock frequency: 96000000Hz */
#define CLK_INIT_ROSC_CLOCK                           32768U  /*!< ROSC clock frequency: 32768Hz */

/*! @brief SCG set for clk_init configuration.
 */
extern const scg_sys_clk_config_t g_sysClkConfig_clk_init;
/*! @brief System OSC set for clk_init configuration.
 */
extern const scg_sosc_config_t g_scgSysOscConfig_clk_init;
/*! @brief SIRC set for clk_init configuration.
 */
extern const scg_sirc_config_t g_scgSircConfig_clk_init;
/*! @brief FIRC set for clk_init configuration.
 */
extern const scg_firc_config_t g_scgFircConfig_clk_init;

/*******************************************************************************
 * API for clk_init configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void clk_init(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

#endif /* _CLOCK_CONFIG_H_ */

