/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_clock.h"
#include "fsl_tpm.h"
#include "fsl_gpio.h"
#include "fsl_lpit.h"
#include "fsl_vref.h"
#include "fsl_lpadc.h"
#include "fsl_lpi2c.h"
#include "fsl_syspm.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for periph_init functional group */
/* Definition of peripheral ID */
#define TPM0_PERIPHERAL TPM0
/* Definition of the clock source frequency */
#define TPM0_CLOCK_SOURCE 24000000UL
/* TPM0 interrupt vector ID (number). */
#define TPM0_IRQN TPM0_IRQn
/* TPM0 interrupt handler identifier. */
#define TPM0_IRQHANDLER TPM0_IRQHandler
/* Definition of TPM0 channel/pair number 0 on Edge-aligned PWM */
#define TPM0_RED_CHANNEL kTPM_Chnl_0
/* Definition of TPM0 channel/pair number 2 on Edge-aligned PWM */
#define TPM0_GREEN_CHANNEL kTPM_Chnl_2
/* Definition of TPM0 channel/pair number 1 on Edge-aligned PWM */
#define TPM0_BLUE_CHANNEL kTPM_Chnl_1
/* Alias for GPIOC peripheral */
#define GPIOC_GPIO GPIOC
/* Alias for PORTC */
#define GPIOC_PORT PORTC
/* GPIOC interrupt vector ID (number). */
#define GPIOC_INT_0_IRQN GPIOC_INT0_IRQn
/* GPIOC interrupt handler identifier. */
#define GPIOC_INT_0_IRQHANDLER GPIOC_INT0_IRQHandler
/* Alias for GPIOD peripheral */
#define GPIOD_GPIO GPIOD
/* Alias for PORTD */
#define GPIOD_PORT PORTD
/* GPIOD interrupt vector ID (number). */
#define GPIOD_INT_0_IRQN GPIOD_INT0_IRQn
/* GPIOD interrupt handler identifier. */
#define GPIOD_INT_0_IRQHANDLER GPIOD_INT0_IRQHandler
/* periph_init defines for LPIT0 */
/* Definition of peripheral ID. */
#define LPIT0_PERIPHERAL LPIT0
/* Definition of clock source frequency. */
#define LPIT0_CLK_FREQ 192000000UL
/* Definition of ticks count for channel adc_conv_trig. */
#define LPIT0_ADC_CONV_TRIG_TICKS 1919999U
/* Definition of channel kLPIT_Chnl_0 ID */
#define LPIT0_ADC_CONV_TRIG kLPIT_Chnl_0
/* Definition of peripheral ID */
#define VREF0_PERIPHERAL VREF0
/* Alias for ADC0 peripheral */
#define ADC0_PERIPHERAL ADC0
/* ADC0 interrupt vector ID (number). */
#define ADC0_IRQN ADC0_IRQn
/* ADC0 interrupt handler identifier. */
#define ADC0_IRQHANDLER ADC0_IRQHandler
/* Command 1 - cmd1 */
#define ADC0_CMD1 1U
/* Trigger 0 - trg0 */
#define ADC0_TRG0 0U
/* periph_init defines for LPI2C1 */
/* Definition of peripheral ID */
#define LPI2C1_PERIPHERAL LPI2C1
/* Definition of clock source */
#define LPI2C1_CLOCK_FREQ 96000000UL
/* Transfer buffer size */
#define LPI2C1_MASTER_BUFFER_SIZE 1
/* Definition of follower address */
#define LPI2C1_MASTER_SLAVE_ADDRESS 0
/* periph_init defines for SYSPM */
/* Definition of peripheral ID */
#define SYSPM_PERIPHERAL SYSPM
/* Definition of SYSPM monitor 0 event Event 1 device CM33 PC (event ID: bcc_tk_bra, ID hex: 0xC, event code: 0b0001100) */
#define SYSPM_MONITOR0_MON0_EVT1_ID 0xCU
/* Definition of SYSPM monitor 0 event Event 2 device CM33 PC (event ID: tcm_opx, ID hex: 0x23, event code: 0b0100011) */
#define SYSPM_MONITOR0_MON0_EVT2_ID 0x23U
/* Definition of SYSPM monitor 0 event Event 3 device CM33 PC (event ID: cycle_count, ID hex: 0x7F, event code: 0b1111111) */
#define SYSPM_MONITOR0_MON0_EVT3_ID 0x7FU
/* Definition of SYSPM monitor 1 event Event 1 device CM33 PS (event ID: bcc_tk_bra, ID hex: 0xC, event code: 0b0001100) */
#define SYSPM_MONITOR1_MON1_EVT1_ID 0xCU
/* Definition of SYSPM monitor 1 event Event 2 device CM33 PS (event ID: tcm_opx, ID hex: 0x23, event code: 0b0100011) */
#define SYSPM_MONITOR1_MON1_EVT2_ID 0x23U
/* Definition of SYSPM monitor 1 event Event 3 device CM33 PS (event ID: cycle_count, ID hex: 0x7F, event code: 0b1111111) */
#define SYSPM_MONITOR1_MON1_EVT3_ID 0x7FU

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const tpm_config_t TPM0_config;
extern const lpit_config_t LPIT0_config;
extern const lpit_chnl_params_t LPIT0_adc_conv_trig_struct;
extern const lpadc_config_t ADC0_config;
extern lpadc_conv_command_config_t ADC0_commandsConfig[1];
extern lpadc_conv_trigger_config_t ADC0_triggersConfig[1];
extern const lpi2c_master_config_t LPI2C1_masterConfig;
extern lpi2c_master_transfer_t LPI2C1_masterTransfer;
extern uint8_t LPI2C1_masterBuffer[LPI2C1_MASTER_BUFFER_SIZE];
extern lpi2c_master_handle_t LPI2C1_masterHandle;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void periph_init(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
