/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: MCXW716CxxxA
package_id: MCXW716CMFTA
mcu_data: ksdk2_0
processor_version: 25.06.10
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 4d8da21c-86cc-4fc1-b018-4794c941d752
  called_from_default_init: true
  selectedCore: cm33
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * TPM0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'TPM0'
- type: 'tpm'
- mode: 'EdgeAligned'
- custom_name_enabled: 'false'
- type_id: 'tpm_2.2.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'TPM0'
- config_sets:
  - tpm_main_config:
    - tpm_config:
      - clockSource: 'kTPM_SystemClock'
      - tpmSrcClkFreq: 'ClocksTool_DefaultInit'
      - prescale: 'kTPM_Prescale_Divide_2'
      - timerFrequency: '1000'
      - useGlobalTimeBase: 'false'
      - syncGlobalTimeBase: 'false'
      - triggerSelect: 'kTPM_Trigger_Select_0'
      - extTriggerPolarity: 'kTPM_ExtTrigger_Active_High'
      - triggerSource: 'kTPM_TriggerSource_Internal'
      - enableDoze: 'false'
      - enableDebugMode: 'true'
      - enableReloadOnTrigger: 'false'
      - enableStopOnOverflow: 'false'
      - enableStartOnTrigger: 'false'
      - enablePauseOnTrigger: 'false'
    - channelGlobalSetting:
      - channelPolarity:
        - 0: 'noInit'
        - 1: 'noInit'
        - 2: 'noInit'
        - 3: 'noInit'
        - 4: 'noInit'
        - 5: 'noInit'
      - channelTrigger:
        - 0: 'noInit'
        - 1: 'noInit'
        - 2: 'noInit'
        - 3: 'noInit'
        - 4: 'noInit'
        - 5: 'noInit'
    - timer_interrupts: ''
    - enable_irq: 'false'
    - tpm_interrupt:
      - IRQn: 'TPM0_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - EnableTimerInInit: 'true'
  - tpm_edge_aligned_mode:
    - tpm_edge_aligned_channels_config:
      - 0:
        - channelId: 'RED'
        - edge_aligned_mode: 'kTPM_EdgeAlignedPwm'
        - edge_aligned_pwm:
          - chnlNumber: 'kTPM_Chnl_0'
          - level: 'kTPM_LowTrue'
          - pauseLevel: 'kTPM_SetOnPause'
          - dutyCyclePercent: '0'
          - enable_chan_irq: 'false'
      - 1:
        - channelId: 'GREEN'
        - edge_aligned_mode: 'kTPM_EdgeAlignedPwm'
        - edge_aligned_pwm:
          - chnlNumber: 'kTPM_Chnl_2'
          - level: 'kTPM_LowTrue'
          - pauseLevel: 'kTPM_SetOnPause'
          - dutyCyclePercent: '0'
          - enable_chan_irq: 'false'
      - 2:
        - channelId: 'BLUE'
        - edge_aligned_mode: 'kTPM_EdgeAlignedPwm'
        - edge_aligned_pwm:
          - chnlNumber: 'kTPM_Chnl_1'
          - level: 'kTPM_LowTrue'
          - pauseLevel: 'kTPM_SetOnPause'
          - dutyCyclePercent: '0'
          - enable_chan_irq: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const tpm_config_t TPM0_config = {
  .prescale = kTPM_Prescale_Divide_2,
  .useGlobalTimeBase = false,
  .syncGlobalTimeBase = false,
  .triggerSelect = kTPM_Trigger_Select_0,
  .extTriggerPolarity = kTPM_ExtTrigger_Active_High,
  .triggerSource = kTPM_TriggerSource_Internal,
  .enableDoze = false,
  .enableDebugMode = true,
  .enableReloadOnTrigger = false,
  .enableStopOnOverflow = false,
  .enableStartOnTrigger = false,
  .enablePauseOnTrigger = false
};

const tpm_chnl_pwm_signal_param_t TPM0_pwmSignalParams[] = { 
  {
    .chnlNumber = kTPM_Chnl_0,
    .level = kTPM_LowTrue,
    .pauseLevel = kTPM_SetOnPause,
    .enableComplementary = false,
    .secPauseLevel = kTPM_ClearOnPause,
    .dutyCyclePercent = 0U,
  },
  {
    .chnlNumber = kTPM_Chnl_2,
    .level = kTPM_LowTrue,
    .pauseLevel = kTPM_SetOnPause,
    .enableComplementary = false,
    .secPauseLevel = kTPM_ClearOnPause,
    .dutyCyclePercent = 0U,
  },
  {
    .chnlNumber = kTPM_Chnl_1,
    .level = kTPM_LowTrue,
    .pauseLevel = kTPM_SetOnPause,
    .enableComplementary = false,
    .secPauseLevel = kTPM_ClearOnPause,
    .dutyCyclePercent = 0U,
  }
};

static void TPM0_init(void) {
  TPM_Init(TPM0_PERIPHERAL, &TPM0_config);
  TPM_SetupPwm(TPM0_PERIPHERAL, TPM0_pwmSignalParams, sizeof(TPM0_pwmSignalParams) / sizeof(tpm_chnl_pwm_signal_param_t), kTPM_EdgeAlignedPwm, 1000U, TPM0_CLOCK_SOURCE);
  TPM_StartTimer(TPM0_PERIPHERAL, kTPM_SystemClock);
}

/***********************************************************************************************************************
 * GPIOC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIOC'
- type: 'gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_2.7.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIOC'
- config_sets:
  - fsl_gpio:
    - enable_irq: 'true'
    - port_interrupt:
      - IRQn: 'GPIOC_INT0_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_1: 'false'
    - gpio_interrupt_1:
      - IRQn: 'GPIOC_INT1_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '1'
      - enable_custom_name: 'false'
    - enable_irq_EFT: 'false'
    - port_interrupt_EFT:
      - IRQn: 'PORTC_EFT_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '2'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIOC_init(void) {
  /* Make sure, the clock gate for port C is enabled (e. g. in pin_mux.c) */
  /* Enable interrupt GPIOC_INT_0_IRQN request in the NVIC */
  EnableIRQ(GPIOC_INT_0_IRQN);
}

/***********************************************************************************************************************
 * GPIOD initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIOD'
- type: 'gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_2.7.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIOD'
- config_sets:
  - fsl_gpio:
    - enable_irq: 'true'
    - port_interrupt:
      - IRQn: 'GPIOD_INT0_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_1: 'false'
    - gpio_interrupt_1:
      - IRQn: 'GPIOA_INT1_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '1'
      - enable_custom_name: 'false'
    - enable_irq_EFT: 'false'
    - port_interrupt_EFT:
      - IRQn: 'PORTA_EFT_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '2'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIOD_init(void) {
  /* Make sure, the clock gate for port D is enabled (e. g. in pin_mux.c) */
  /* Enable interrupt GPIOD_INT_0_IRQN request in the NVIC */
  EnableIRQ(GPIOD_INT_0_IRQN);
}

/***********************************************************************************************************************
 * LPIT0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPIT0'
- type: 'lpit'
- mode: 'LPIT_GENERAL'
- custom_name_enabled: 'false'
- type_id: 'lpit_2.0.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPIT0'
- config_sets:
  - fsl_lpit:
    - lpitConfig:
      - enableRunInDebug: 'false'
      - enableRunInDoze: 'false'
    - timingConfig:
      - clockSource: 'AsyncPeripheralClock'
      - clockSourceFreq: 'BOARD_BootClockRUN'
    - channels:
      - 0:
        - lpitChannelPrefixID: 'adc_conv_trig'
        - channelNumber: '0'
        - enableChain: 'false'
        - timerMode: 'kLPIT_PeriodicCounter'
        - timerPeriod: '10 ms'
        - lpit_trigger_select_t: 'internal_trigger_0'
        - enableReloadOnTriggerBool: 'false'
        - enableStopOnTimeout: 'false'
        - enableStartOnTriggerBool: 'false'
        - startTimer: 'false'
        - enableInterrupt: 'false'
    - enableSharedInterrupt: 'false'
    - sharedInterrupt:
      - IRQn: 'LPIT0_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpit_chnl_params_t LPIT0_adc_conv_trig_struct = {
  .chainChannel = false,
  .timerMode = kLPIT_PeriodicCounter,
  .triggerSource = kLPIT_TriggerSource_Internal,
  .triggerSelect = kLPIT_Trigger_TimerChn0,
  .enableReloadOnTrigger = false,
  .enableStopOnTimeout = false,
  .enableStartOnTrigger = false
};
const lpit_config_t LPIT0_config = {
  .enableRunInDebug = false,
  .enableRunInDoze = false
};

static void LPIT0_init(void) {
  /* Initialize the LPIT. */
  LPIT_Init(LPIT0_PERIPHERAL, &LPIT0_config);
  /* Setup channel 0. */
  LPIT_SetupChannel(LPIT0_PERIPHERAL, LPIT0_ADC_CONV_TRIG, &LPIT0_adc_conv_trig_struct);
  /* Set channel 0 period to 1920000 ticks. */
  LPIT_SetTimerPeriod(LPIT0_PERIPHERAL, LPIT0_ADC_CONV_TRIG, LPIT0_ADC_CONV_TRIG_TICKS);
}

/***********************************************************************************************************************
 * VREF0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'VREF0'
- type: 'vref_1'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'vref_1_2.4.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'VREF0'
- config_sets:
  - fsl_vref:
    - vref_config:
      - bufferMode: 'kVREF_ModeHighPowerBuffer'
      - enableLowPowerBuff: 'true'
      - enableInternalVoltageRegulator: 'true'
      - enableChopOscillator: 'true'
      - enableHCBandgap: 'true'
      - enableCurvatureCompensation: 'true'
      - initTrim: 'false'
    - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const vref_config_t VREF0_config = {
  .bufferMode = kVREF_ModeHighPowerBuffer,
  .enableLowPowerBuff = true,
  .enableInternalVoltageRegulator = true,
  .enableChopOscillator = true,
  .enableHCBandgap = true,
  .enableCurvatureCompensation = true
};

static void VREF0_init(void) {
  /* VREF0 peripheral initialization */
  VREF_Init(VREF0_PERIPHERAL, &VREF0_config);
}

/***********************************************************************************************************************
 * ADC0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC0'
- type: 'lpadc'
- mode: 'LPADC'
- custom_name_enabled: 'false'
- type_id: 'lpadc_2.8.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC0'
- config_sets:
  - fsl_lpadc:
    - lpadcConfig:
      - clockSource: 'AsynchronousFunctionClock'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - enableInDozeMode: 'false'
      - conversionAverageMode: 'kLPADC_ConversionAverage128'
      - offsetCalibration: 'yes'
      - autoCalibrate: 'true'
      - enableAnalogPreliminary: 'true'
      - powerUpDelay: '0x80'
      - referenceVoltageSource: 'kLPADC_ReferenceVoltageAlt1'
      - powerLevelMode: 'kLPADC_PowerLevelAlt4'
      - triggerPriorityPolicy: 'kLPADC_TriggerPriorityExceptionDisabled'
      - enableConvPause: 'false'
      - convPauseDelay: '0'
      - FIFO0Watermark: '0'
      - FIFO1Watermark: '0'
      - FIFO0WatermarkDMA: 'false'
      - FIFO1WatermarkDMA: 'false'
    - lpadcConvCommandConfig:
      - 0:
        - user_commandId: ''
        - commandId: '1'
        - chainedNextCommandNumber: '0'
        - sampleChannelMode: 'kLPADC_SampleChannelSingleEndSideB'
        - channelNumber: 'B.6'
        - enableAutoChannelIncrement: 'false'
        - loopCount: '0'
        - hardwareAverageMode: 'kLPADC_HardwareAverageCount1'
        - sampleTimeMode: 'kLPADC_SampleTimeADCK131'
        - hardwareCompareMode: 'kLPADC_HardwareCompareDisabled'
        - hardwareCompareValueHigh: '0'
        - hardwareCompareValueLow: '0'
        - conversionResoultuionMode: 'kLPADC_ConversionResolutionHigh'
        - enableWaitTrigger: 'true'
    - lpadcConvTriggerConfig:
      - 0:
        - user_triggerId: ''
        - triggerId: '0'
        - targetCommandId: '1'
        - delayPower: '0'
        - priority: 'false'
        - channelAFIFOSelect: '0'
        - channelBFIFOSelect: '1'
        - enableHardwareTrigger: 'true'
    - IRQ_cfg:
      - interrupt_type: 'kLPADC_Trigger0CompletionInterruptEnable'
      - enable_irq: 'true'
      - adc_interrupt:
        - IRQn: 'ADC0_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpadc_config_t ADC0_config = {
  .enableInDozeMode = false,
  .conversionAverageMode = kLPADC_ConversionAverage128,
  .enableAnalogPreliminary = true,
  .powerUpDelay = 0x80UL,
  .referenceVoltageSource = kLPADC_ReferenceVoltageAlt1,
  .powerLevelMode = kLPADC_PowerLevelAlt4,
  .triggerPriorityPolicy = kLPADC_TriggerPriorityExceptionDisabled,
  .enableConvPause = false,
  .convPauseDelay = 0UL,
  .FIFO0Watermark = 0UL,
  .FIFO1Watermark = 0UL
};
lpadc_conv_command_config_t ADC0_commandsConfig[1] = {
  {
    .sampleChannelMode = kLPADC_SampleChannelSingleEndSideB,
    .channelNumber = 6U,
    .chainedNextCommandNumber = 0,
    .enableAutoChannelIncrement = false,
    .loopCount = 0UL,
    .hardwareAverageMode = kLPADC_HardwareAverageCount1,
    .sampleTimeMode = kLPADC_SampleTimeADCK131,
    .hardwareCompareMode = kLPADC_HardwareCompareDisabled,
    .hardwareCompareValueHigh = 0UL,
    .hardwareCompareValueLow = 0UL,
    .conversionResolutionMode = kLPADC_ConversionResolutionHigh,
    .enableWaitTrigger = true
  }
};
lpadc_conv_trigger_config_t ADC0_triggersConfig[1] = {
  {
    .targetCommandId = 1,
    .delayPower = 0UL,
    .channelAFIFOSelect = 0,
    .channelBFIFOSelect = 1,
    .priority = 1,
    .enableHardwareTrigger = true
  }
};

static void ADC0_init(void) {
  /* Initialize LPADC converter */
  LPADC_Init(ADC0_PERIPHERAL, &ADC0_config);
  /* Perform offset calibration */
  LPADC_DoOffsetCalibration(ADC0_PERIPHERAL);
  /* Perform auto calibration */
  LPADC_DoAutoCalibration(ADC0_PERIPHERAL);
  /* Configure conversion command 1. */
  LPADC_SetConvCommandConfig(ADC0_PERIPHERAL, 1, &ADC0_commandsConfig[0]);
  /* Configure trigger 0. */
  LPADC_SetConvTriggerConfig(ADC0_PERIPHERAL, 0, &ADC0_triggersConfig[0]);
  /* Enable interrupts from LPADC */
  LPADC_EnableInterrupts(ADC0_PERIPHERAL, (kLPADC_Trigger0CompletionInterruptEnable));
  /* Enable interrupt ADC0_IRQN request in the NVIC */
  EnableIRQ(ADC0_IRQN);
}

/***********************************************************************************************************************
 * LPI2C1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPI2C1'
- type: 'lpi2c'
- mode: 'master'
- custom_name_enabled: 'false'
- type_id: 'lpi2c_2.2.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPI2C1'
- config_sets:
  - main:
    - clockSource: 'Lpi2cClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
  - interrupt_vector: []
  - master:
    - mode: 'transfer'
    - config:
      - enableMaster: 'true'
      - enableDoze: 'true'
      - debugEnable: 'false'
      - ignoreAck: 'false'
      - pinConfig: 'kLPI2C_2PinOpenDrain'
      - baudRate_Hz: '400000'
      - busIdleTimeout_ns: '0'
      - pinLowTimeout_ns: '0'
      - sdaGlitchFilterWidth_ns: '0'
      - sclGlitchFilterWidth_ns: '0'
      - hostRequest:
        - enable: 'false'
        - source: 'kLPI2C_HostRequestExternalPin'
        - polarity: 'kLPI2C_HostRequestPinActiveHigh'
      - edmaRequestSources: ''
    - transfer:
      - blocking: 'false'
      - enable_custom_handle: 'false'
      - callback:
        - name: ''
        - userData: ''
      - flags: ''
      - slaveAddress: '0'
      - direction: 'kLPI2C_Write'
      - subaddress: '0'
      - subaddressSize: '0'
      - blocking_buffer: 'false'
      - enable_custom_buffer: 'false'
      - dataSize: '1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpi2c_master_config_t LPI2C1_masterConfig = {
  .enableMaster = true,
  .enableDoze = true,
  .debugEnable = false,
  .ignoreAck = false,
  .pinConfig = kLPI2C_2PinOpenDrain,
  .baudRate_Hz = 400000UL,
  .busIdleTimeout_ns = 0UL,
  .pinLowTimeout_ns = 0UL,
  .sdaGlitchFilterWidth_ns = 0U,
  .sclGlitchFilterWidth_ns = 0U,
  .hostRequest = {
    .enable = false,
    .source = kLPI2C_HostRequestExternalPin,
    .polarity = kLPI2C_HostRequestPinActiveHigh
  }
};
lpi2c_master_transfer_t LPI2C1_masterTransfer = {
  .flags = kLPI2C_TransferDefaultFlag,
  .slaveAddress = 0,
  .direction = kLPI2C_Write,
  .subaddress = 0,
  .subaddressSize = 0,
  .data = LPI2C1_masterBuffer,
  .dataSize = 1
};
lpi2c_master_handle_t LPI2C1_masterHandle;
uint8_t LPI2C1_masterBuffer[LPI2C1_MASTER_BUFFER_SIZE];

static void LPI2C1_init(void) {
  LPI2C_MasterInit(LPI2C1_PERIPHERAL, &LPI2C1_masterConfig, LPI2C1_CLOCK_FREQ);
  LPI2C_MasterTransferCreateHandle(LPI2C1_PERIPHERAL, &LPI2C1_masterHandle, NULL, NULL);
}

/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
      - 2: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  TPM0_init();
  GPIOC_init();
  GPIOD_init();
  LPIT0_init();
  VREF0_init();
  ADC0_init();
  LPI2C1_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
