/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define ICR6_IRQS_irqs0 0x00u /*!<@brief Interrupt Select: Interrupt/trigger output/DMA request 0. */
#define PCR_DSE_dse1 0x01u    /*!<@brief Drive Strength Enable: High */
#define PCR_PE_pe1 0x01u      /*!<@brief Pull Enable: Enables */
#define PCR_PS_ps1 0x01u      /*!<@brief Pull Select: Enables internal pullup resistor */

/*! @name PORTA21 (number 18), rgb_r
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_rgb_r_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_rgb_r_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_rgb_r_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTA20 (number 17), rgb_b
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_rgb_b_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_rgb_b_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_rgb_b_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTA19 (number 14), rgb_g
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_rgb_g_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_rgb_g_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_rgb_g_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTC6 (number 44), sw2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_sw2_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_sw2_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_sw2_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_sw2_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_sw2_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTC1 (number 38), user_led
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_user_led_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_user_led_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_user_led_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_user_led_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_user_led_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_user_led_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTD3 (number 26), light_sens
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_light_sens_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_light_sens_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_light_sens_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTD1 (number 24), sw4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_sw4_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_sw4_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_sw4_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_sw4_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_sw4_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*!
 * @brief 
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
