/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MCXW716CxxxA
package_id: MCXW716CMFTA
mcu_data: ksdk2_0
processor_version: 25.06.10
external_user_signals: {}
pin_labels:
- {pin_num: '44', pin_signal: ADC0_A8/PTC6/WUU0_P11/LPSPI1_PCS1/TPM1_CH5/FLEXIO0_D22, label: sw2, identifier: sw2}
- {pin_num: '38', pin_signal: PTC1/WUU0_P8/LPSPI1_PCS3/CAN0_RX/I3C0_SCL/TPM1_CH1/LPI2C1_SDA/FLEXIO0_D17, label: user_led, identifier: d14;user_led}
- {pin_num: '18', pin_signal: ADC0_A15/CMP0_IN2/PTA21/WUU0_P5/LPSPI0_PCS3/LPUART0_RX/EWM0_OUT_b/TPM0_CH0/RF_GPO_3/RF_GPO_7/FLEXIO0_D8/RF_GPO_10, label: rgb_r, identifier: rgb_r}
- {pin_num: '17', pin_signal: ADC0_A14/CMP0_IN3/PTA20/LPSPI0_PCS2/LPUART0_TX/EWM0_IN/TPM0_CH1/RF_GPO_2/FLEXIO0_D7, label: rgb_b, identifier: rgb_b}
- {pin_num: '14', pin_signal: CMP1_IN0/PTA19/WUU0_P4/LPSPI0_SCK/LPUART0_RTS_b/LPI2C0_SCL/TPM0_CH2/RF_GPO_1, label: rgb_g, identifier: rgb_g}
- {pin_num: '26', pin_signal: ADC0_B6/PTD3/LPTMR1_ALT3/TAMPER1/RF_GPO_6/TRGMUX0_IN2, label: light_sens, identifier: light_sens}
- {pin_num: '24', pin_signal: ADC0_B5/PTD1/SPC0_LPREQ/NMI_b/RF_GPO_4, label: sw4, identifier: sw4}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "fsl_trgmux.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: '18', peripheral: TPM0, signal: 'CH, 0', pin_signal: ADC0_A15/CMP0_IN2/PTA21/WUU0_P5/LPSPI0_PCS3/LPUART0_RX/EWM0_OUT_b/TPM0_CH0/RF_GPO_3/RF_GPO_7/FLEXIO0_D8/RF_GPO_10,
    drive_strength: high}
  - {pin_num: '17', peripheral: TPM0, signal: 'CH, 1', pin_signal: ADC0_A14/CMP0_IN3/PTA20/LPSPI0_PCS2/LPUART0_TX/EWM0_IN/TPM0_CH1/RF_GPO_2/FLEXIO0_D7, drive_strength: high}
  - {pin_num: '14', peripheral: TPM0, signal: 'CH, 2', pin_signal: CMP1_IN0/PTA19/WUU0_P4/LPSPI0_SCK/LPUART0_RTS_b/LPI2C0_SCL/TPM0_CH2/RF_GPO_1, drive_strength: high}
  - {pin_num: '44', peripheral: GPIOC, signal: 'GPIO, 6', pin_signal: ADC0_A8/PTC6/WUU0_P11/LPSPI1_PCS1/TPM1_CH5/FLEXIO0_D22, direction: INPUT, gpio_per_interrupt_sel: output0,
    gpio_per_interrupt: kGPIO_InterruptFallingEdge, pull_select: up, pull_enable: enable}
  - {pin_num: '38', peripheral: GPIOC, signal: 'GPIO, 1', pin_signal: PTC1/WUU0_P8/LPSPI1_PCS3/CAN0_RX/I3C0_SCL/TPM1_CH1/LPI2C1_SDA/FLEXIO0_D17, identifier: user_led,
    direction: OUTPUT, gpio_init_state: 'true', drive_strength: high}
  - {pin_num: '26', peripheral: ADC0, signal: 'B, 6', pin_signal: ADC0_B6/PTD3/LPTMR1_ALT3/TAMPER1/RF_GPO_6/TRGMUX0_IN2}
  - {peripheral: ADC0, signal: 'TRG_CH, 0', pin_signal: TRGMUX0_LPIT0_CH0}
  - {pin_num: '24', peripheral: GPIOD, signal: 'GPIO, 1', pin_signal: ADC0_B5/PTD1/SPC0_LPREQ/NMI_b/RF_GPO_4, direction: INPUT, gpio_per_interrupt: kGPIO_InterruptFallingEdge}
  - {pin_num: '2', peripheral: LPI2C1, signal: SDA, pin_signal: PTB4/WUU0_P15/LPSPI1_PCS3/LPUART1_CTS_b/LPI2C1_SDA/I3C0_SDA/TRGMUX0_IN0/FLEXIO0_D30}
  - {pin_num: '3', peripheral: LPI2C1, signal: SCL, pin_signal: PTB5/LPSPI1_PCS2/LPUART1_RTS_b/LPI2C1_SCL/I3C0_SCL/TRGMUX0_OUT0/FLEXIO0_D31}
  - {pin_num: '40', peripheral: LPUART1, signal: TX, pin_signal: PTC3/LPSPI1_SCK/LPUART1_TX/LPI2C1_SDAS/TPM1_CH3/FLEXIO0_D19}
  - {pin_num: '39', peripheral: LPUART1, signal: RX, pin_signal: PTC2/WUU0_P9/LPSPI1_SOUT/LPUART1_RX/LPI2C1_SCLS/TPM1_CH2/I3C0_PUR/FLEXIO0_D18}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : 
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Clock Configuration: Peripheral clocks are enabled; module does not stall low power mode entry */
    CLOCK_EnableClock(kCLOCK_GpioC);
    /* Clock Configuration: Peripheral clocks are enabled; module does not stall low power mode entry */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Clock Configuration: Peripheral clocks are enabled; module does not stall low power mode entry */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Clock Configuration: Peripheral clocks are enabled; module does not stall low power mode entry */
    CLOCK_EnableClock(kCLOCK_PortC);

    gpio_pin_config_t user_led_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTC1 (pin 38)  */
    GPIO_PinInit(BOARD_INITPINS_user_led_GPIO, BOARD_INITPINS_user_led_PIN, &user_led_config);

    gpio_pin_config_t sw2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC6 (pin 44)  */
    GPIO_PinInit(BOARD_INITPINS_sw2_GPIO, BOARD_INITPINS_sw2_PIN, &sw2_config);

    gpio_pin_config_t sw4_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD1 (pin 24)  */
    GPIO_PinInit(BOARD_INITPINS_sw4_GPIO, BOARD_INITPINS_sw4_PIN, &sw4_config);

    GPIOC->ICR[6] = ((GPIOC->ICR[6] &
                      /* Mask bits to zero which are setting */
                      (~(GPIO_ICR_IRQS_MASK | GPIO_ICR_ISF_MASK)))

                     /* Interrupt Select: Interrupt/trigger output/DMA request 0. */
                     | GPIO_ICR_IRQS(ICR6_IRQS_irqs0));

    /* Interrupt configuration on GPIOC6 (pin 44): Interrupt on falling edge */
    GPIO_SetPinInterruptConfig(BOARD_INITPINS_sw2_GPIO, BOARD_INITPINS_sw2_PIN, kGPIO_InterruptFallingEdge);

    /* Interrupt configuration on GPIOD1 (pin 24): Interrupt on falling edge */
    GPIO_SetPinInterruptConfig(BOARD_INITPINS_sw4_GPIO, BOARD_INITPINS_sw4_PIN, kGPIO_InterruptFallingEdge);

    /* PORTA19 (pin 14) is configured as TPM0_CH2 */
    PORT_SetPinMux(BOARD_INITPINS_rgb_g_PORT, BOARD_INITPINS_rgb_g_PIN, kPORT_MuxAlt5);

    PORTA->PCR[19] = ((PORTA->PCR[19] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_DSE_MASK)))

                      /* Drive Strength Enable: High. */
                      | PORT_PCR_DSE(PCR_DSE_dse1));

    /* PORTA20 (pin 17) is configured as TPM0_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_rgb_b_PORT, BOARD_INITPINS_rgb_b_PIN, kPORT_MuxAlt5);

    PORTA->PCR[20] = ((PORTA->PCR[20] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_DSE_MASK)))

                      /* Drive Strength Enable: High. */
                      | PORT_PCR_DSE(PCR_DSE_dse1));

    /* PORTA21 (pin 18) is configured as TPM0_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_rgb_r_PORT, BOARD_INITPINS_rgb_r_PIN, kPORT_MuxAlt5);

    PORTA->PCR[21] = ((PORTA->PCR[21] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_DSE_MASK)))

                      /* Drive Strength Enable: High. */
                      | PORT_PCR_DSE(PCR_DSE_dse1));

    /* PORTB4 (pin 2) is configured as LPI2C1_SDA */
    PORT_SetPinMux(PORTB, 4U, kPORT_MuxAlt4);

    /* PORTB5 (pin 3) is configured as LPI2C1_SCL */
    PORT_SetPinMux(PORTB, 5U, kPORT_MuxAlt4);

    /* PORTC1 (pin 38) is configured as PTC1 */
    PORT_SetPinMux(BOARD_INITPINS_user_led_PORT, BOARD_INITPINS_user_led_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[1] = ((PORTC->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK)))

                     /* Drive Strength Enable: High. */
                     | PORT_PCR_DSE(PCR_DSE_dse1));

    /* PORTC2 (pin 39) is configured as LPUART1_RX */
    PORT_SetPinMux(PORTC, 2U, kPORT_MuxAlt3);

    /* PORTC3 (pin 40) is configured as LPUART1_TX */
    PORT_SetPinMux(PORTC, 3U, kPORT_MuxAlt3);

    /* PORTC6 (pin 44) is configured as PTC6 */
    PORT_SetPinMux(BOARD_INITPINS_sw2_PORT, BOARD_INITPINS_sw2_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[6] = ((PORTC->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK)))

                     /* Pull Select: Enables internal pullup resistor. */
                     | PORT_PCR_PS(PCR_PS_ps1)

                     /* Pull Enable: Enables. */
                     | PORT_PCR_PE(PCR_PE_pe1));

    /* PORTD1 (pin 24) is configured as PTD1 */
    PORT_SetPinMux(BOARD_INITPINS_sw4_PORT, BOARD_INITPINS_sw4_PIN, kPORT_MuxAsGpio);

    /* PORTD3 (pin 26) is configured as ADC0_B6 */
    PORT_SetPinMux(BOARD_INITPINS_light_sens_PORT, BOARD_INITPINS_light_sens_PIN, kPORT_PinDisabledOrAnalog);
    /* LPIT0 Channel 0 is selected as ADC_GP0 device trigger input 0 */
    TRGMUX_SetTriggerSource(TRGMUX0, kTRGMUX_Trgmux0AdcGp0, kTRGMUX_TriggerInput0, kTRGMUX_SourceLpit0Channel0);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
