/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define ICR7_IRQS_irqs1 0x01u /*!<@brief Interrupt Select: Interrupt/trigger output/DMA request 1. */
#define PCR_DSE_dse1 0x01u    /*!<@brief Drive Strength Enable: High */
#define PCR_PE_pe1 0x01u      /*!<@brief Pull Enable: Enables */
#define PCR_PS_ps1 0x01u      /*!<@brief Pull Select: Enables internal pullup resistor */

/*! @name PORTA21 (number 18), RGB_R
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RGB_R_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RGB_R_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RGB_R_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTA20 (number 17), RGB_B
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RGB_B_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RGB_B_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RGB_B_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTA19 (number 14), RGB_G
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RGB_G_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RGB_G_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RGB_G_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTC1 (number 38), USER_LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_LED_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_LED_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_USER_LED_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_USER_LED_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_USER_LED_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_USER_LED_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTC7 (number 45), ACC_INT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ACC_INT_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ACC_INT_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ACC_INT_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ACC_INT_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ACC_INT_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTC6 (number 44), SW2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW2_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW2_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SW2_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW2_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW2_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTD1 (number 24), SW4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW4_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW4_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SW4_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW4_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW4_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTD3 (number 26), LIGHT_SENS
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LIGHT_SENS_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LIGHT_SENS_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LIGHT_SENS_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief 
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
